// Must run before Tailwind CSS is loaded to ensure the configuration is applied correctly
window.tailwind = window.tailwind || {};
tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "primary": "#005b9d",
                "primary-container": "#1f74bf",
                "secondary-fixed": "#cde5ff",
                "background": "#f8f9ff",
                "on-background": "#191c21",
                "surface": "#f8f9ff",
                "surface-container": "#eceef4",
                "outline": "#717782",
                "outline-variant": "#c1c7d3",
                "tertiary-container": "#ab5d00",
                "on-primary-container": "#f4f7ff",
                "surface-tint": "#0061a6",
                "on-error-container": "#93000a",
                "inverse-primary": "#a0c9ff",
                "on-tertiary-container": "#fff5ef",
                "error": "#ba1a1a",
                "background": "#f8f9ff",
                "on-primary-fixed-variant": "#00497f",
                "on-secondary-container": "#00476f",
                "inverse-surface": "#2d3136",
                "secondary-fixed": "#cde5ff",
                "primary-container": "#1f74bf",
                "surface-dim": "#d8dae1",
                "on-secondary-fixed-variant": "#004b74",
                "secondary-fixed-dim": "#94ccff",
                "surface-container-lowest": "#ffffff",
                "on-primary": "#ffffff",
                "on-tertiary": "#ffffff",
                "surface-bright": "#f8f9ff",
                "error-container": "#ffdad6",
                "outline-variant": "#c1c7d3",
                "on-background": "#191c21",
                "on-primary-fixed": "#001c37",
                "secondary-container": "#5cb8ff",
                "surface-container-highest": "#e0e2e9",
                "tertiary-fixed-dim": "#ffb77c",
                "on-tertiary-fixed": "#2e1500",
                "secondary": "#006399",
                "on-secondary-fixed": "#001d32",
                "on-surface": "#191c21",
                "outline": "#717782",
                "tertiary": "#874800",
                "primary-fixed": "#d2e4ff",
                "surface-container-low": "#f2f3fa",
                "on-tertiary-fixed-variant": "#6d3900",
                "surface-variant": "#e0e2e9",
                "on-secondary": "#ffffff",
                "primary": "#005b9d",
                "on-surface-variant": "#414751",
                "surface-container-high": "#e6e8ef",
                "tertiary-fixed": "#ffdcc2",
                "inverse-on-surface": "#eff0f7",
                "surface-container": "#eceef4",
                "primary-fixed-dim": "#a0c9ff",
                "on-error": "#ffffff",
                "surface": "#f8f9ff"
            },
            fontFamily: {
                "headline": ["Manrope"],
                "body": ["Inter"],
                "label": ["Inter"]
            },
            borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
        },
    },

}